### ISSUE TITLE
Use WaitForString() timeout in scripts

### ISSUE THREAD

**Issue by jamiecaesar** [PresidioCode/SecureCRT#11]
There is a timeout value that can be passed into WaitForString().  It also has a return code that will indicate if the timeout was reached.  Modify scripts to use this so if something hangs, or if the script isn't seeing the expected text that the script won't hang forever (or until manually cancelled).

**Comment by garibaldi0** [comment]
I can see where this might be a good idea in the GetHostname() function as that's usually the first thing we do.  And with this we could determine that we're not connected to a system and abort the script.

But doing this every time there's a WaitForString() may be a bit much.

There may also be some cases where we need to add the timeout in the main() before we call GetHostname().

**Comment by jamiecaesar** [comment]
Closing -- probably won't be changing anything on this.
